# Generated by Django 4.2 on 2023-05-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadastro_of',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_da_of', models.CharField(max_length=8)),
                ('codigo_produto', models.CharField(max_length=5)),
                ('produto', models.TextField()),
                ('quantidade_of', models.IntegerField()),
            ],
        ),
    ]
