# Generated by Django 4.2 on 2023-07-23 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastro', '0002_cadastro_of_criador'),
    ]

    operations = [
        migrations.CreateModel(
            name='cadastro_produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_produto', models.CharField(max_length=5)),
                ('produto', models.TextField()),
                ('tempo_produto', models.IntegerField()),
                ('criador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='cadastro_of',
        ),
    ]
